name: Lint, Run, and Test

on: [push, pull_request]

jobs:
  lint_run_test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: kemzeb/habiter
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          # Stop build for any Python syntax errors
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Stop build if there any linting errors are raised
          flake8 . --count --max-complexity=10 --max-line-length=120 --statistics 
          
      - name: Build and run
        run: |
          pip install -e .
          habiter add test

      - name: Test
        run: pytest -v

