name: Build & Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GOPATH: "${{ github.workspace }}/go"

jobs:
  build_run_test:
    runs-on: ubuntu-latest
    steps:
      - name: echo $GOPATH 1
        run: |
          echo $GOPATH

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: echo $GOPATH 2
        run: |
          go env GOPATH
