name: Build & Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_run_test:
    env:
      GOPATH: ""

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set $GOPATH
        run: |
          echo $GOPATH
          export GOPATH=$(go env GOPATH)
          echo My new path?: $GOPATH

      - name: $GOPATH. $GOPATH? Again?
        run: |
          echo My path: $GOPATH
