name: Build & Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup $GOPATH
        run: |
          export GOPATH="${{ github.workspace }}/go"
          echo "$GOPATH"
